// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enums/e_db.proto

#include "enums/e_db.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace biot {
}  // namespace biot
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_enums_2fe_5fdb_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_enums_2fe_5fdb_2eproto = nullptr;
const uint32_t TableStruct_enums_2fe_5fdb_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_enums_2fe_5fdb_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020enums/e_db.proto\022\004biot*u\n\rBiotAppDbTyp"
  "e\022\023\n\017DB_TYPE_SQLITE3\020\000\022\023\n\017DB_TYPE_MONGOD"
  "B\020\001\022\021\n\rDB_TYPE_MYSQL\020\002\022\023\n\017DB_TYPE_LEVELD"
  "B\020\003\022\022\n\016DB_TYPE_CUSTOM\020\004b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_enums_2fe_5fdb_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_enums_2fe_5fdb_2eproto = {
    false, false, 151, descriptor_table_protodef_enums_2fe_5fdb_2eproto,
    "enums/e_db.proto",
    &descriptor_table_enums_2fe_5fdb_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_enums_2fe_5fdb_2eproto::offsets,
    nullptr, file_level_enum_descriptors_enums_2fe_5fdb_2eproto,
    file_level_service_descriptors_enums_2fe_5fdb_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_enums_2fe_5fdb_2eproto_getter() {
  return &descriptor_table_enums_2fe_5fdb_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_enums_2fe_5fdb_2eproto(&descriptor_table_enums_2fe_5fdb_2eproto);
namespace biot {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* BiotAppDbType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2fe_5fdb_2eproto);
  return file_level_enum_descriptors_enums_2fe_5fdb_2eproto[0];
}
bool BiotAppDbType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace biot
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
