// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: param_module.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_param_5fmodule_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_param_5fmodule_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "mnetwork.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_param_5fmodule_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_param_5fmodule_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_param_5fmodule_2eproto;
namespace biot {
class BiotAppModule;
struct BiotAppModuleDefaultTypeInternal;
extern BiotAppModuleDefaultTypeInternal _BiotAppModule_default_instance_;
}  // namespace biot
PROTOBUF_NAMESPACE_OPEN
template<> ::biot::BiotAppModule* Arena::CreateMaybeMessage<::biot::BiotAppModule>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace biot {

// ===================================================================

class BiotAppModule final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:biot.BiotAppModule) */ {
 public:
  inline BiotAppModule() : BiotAppModule(nullptr) {}
  ~BiotAppModule() override;
  explicit PROTOBUF_CONSTEXPR BiotAppModule(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BiotAppModule(const BiotAppModule& from);
  BiotAppModule(BiotAppModule&& from) noexcept
    : BiotAppModule() {
    *this = ::std::move(from);
  }

  inline BiotAppModule& operator=(const BiotAppModule& from) {
    CopyFrom(from);
    return *this;
  }
  inline BiotAppModule& operator=(BiotAppModule&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BiotAppModule& default_instance() {
    return *internal_default_instance();
  }
  static inline const BiotAppModule* internal_default_instance() {
    return reinterpret_cast<const BiotAppModule*>(
               &_BiotAppModule_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(BiotAppModule& a, BiotAppModule& b) {
    a.Swap(&b);
  }
  inline void Swap(BiotAppModule* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BiotAppModule* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BiotAppModule* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BiotAppModule>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BiotAppModule& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const BiotAppModule& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BiotAppModule* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "biot.BiotAppModule";
  }
  protected:
  explicit BiotAppModule(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNetworkFieldNumber = 1,
  };
  // .biot.BiotAppNetwork network = 1;
  bool has_network() const;
  private:
  bool _internal_has_network() const;
  public:
  void clear_network();
  const ::biot::BiotAppNetwork& network() const;
  PROTOBUF_NODISCARD ::biot::BiotAppNetwork* release_network();
  ::biot::BiotAppNetwork* mutable_network();
  void set_allocated_network(::biot::BiotAppNetwork* network);
  private:
  const ::biot::BiotAppNetwork& _internal_network() const;
  ::biot::BiotAppNetwork* _internal_mutable_network();
  public:
  void unsafe_arena_set_allocated_network(
      ::biot::BiotAppNetwork* network);
  ::biot::BiotAppNetwork* unsafe_arena_release_network();

  // @@protoc_insertion_point(class_scope:biot.BiotAppModule)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::biot::BiotAppNetwork* network_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_param_5fmodule_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BiotAppModule

// .biot.BiotAppNetwork network = 1;
inline bool BiotAppModule::_internal_has_network() const {
  return this != internal_default_instance() && _impl_.network_ != nullptr;
}
inline bool BiotAppModule::has_network() const {
  return _internal_has_network();
}
inline const ::biot::BiotAppNetwork& BiotAppModule::_internal_network() const {
  const ::biot::BiotAppNetwork* p = _impl_.network_;
  return p != nullptr ? *p : reinterpret_cast<const ::biot::BiotAppNetwork&>(
      ::biot::_BiotAppNetwork_default_instance_);
}
inline const ::biot::BiotAppNetwork& BiotAppModule::network() const {
  // @@protoc_insertion_point(field_get:biot.BiotAppModule.network)
  return _internal_network();
}
inline void BiotAppModule::unsafe_arena_set_allocated_network(
    ::biot::BiotAppNetwork* network) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.network_);
  }
  _impl_.network_ = network;
  if (network) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:biot.BiotAppModule.network)
}
inline ::biot::BiotAppNetwork* BiotAppModule::release_network() {
  
  ::biot::BiotAppNetwork* temp = _impl_.network_;
  _impl_.network_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::biot::BiotAppNetwork* BiotAppModule::unsafe_arena_release_network() {
  // @@protoc_insertion_point(field_release:biot.BiotAppModule.network)
  
  ::biot::BiotAppNetwork* temp = _impl_.network_;
  _impl_.network_ = nullptr;
  return temp;
}
inline ::biot::BiotAppNetwork* BiotAppModule::_internal_mutable_network() {
  
  if (_impl_.network_ == nullptr) {
    auto* p = CreateMaybeMessage<::biot::BiotAppNetwork>(GetArenaForAllocation());
    _impl_.network_ = p;
  }
  return _impl_.network_;
}
inline ::biot::BiotAppNetwork* BiotAppModule::mutable_network() {
  ::biot::BiotAppNetwork* _msg = _internal_mutable_network();
  // @@protoc_insertion_point(field_mutable:biot.BiotAppModule.network)
  return _msg;
}
inline void BiotAppModule::set_allocated_network(::biot::BiotAppNetwork* network) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.network_);
  }
  if (network) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(network));
    if (message_arena != submessage_arena) {
      network = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, network, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.network_ = network;
  // @@protoc_insertion_point(field_set_allocated:biot.BiotAppModule.network)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace biot

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_param_5fmodule_2eproto
