// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: param_module.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_param_5fmodule_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_param_5fmodule_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "module_network.pb.h"
#include "module_device.pb.h"
#include "module_db.pb.h"
#include "module_hw.pb.h"
#include "module_media.pb.h"
#include "module_storage.pb.h"
#include "module_subsys.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_param_5fmodule_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_param_5fmodule_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_param_5fmodule_2eproto;
namespace biot {
class BiotAppModule;
struct BiotAppModuleDefaultTypeInternal;
extern BiotAppModuleDefaultTypeInternal _BiotAppModule_default_instance_;
}  // namespace biot
PROTOBUF_NAMESPACE_OPEN
template<> ::biot::BiotAppModule* Arena::CreateMaybeMessage<::biot::BiotAppModule>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace biot {

// ===================================================================

class BiotAppModule final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:biot.BiotAppModule) */ {
 public:
  inline BiotAppModule() : BiotAppModule(nullptr) {}
  ~BiotAppModule() override;
  explicit PROTOBUF_CONSTEXPR BiotAppModule(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BiotAppModule(const BiotAppModule& from);
  BiotAppModule(BiotAppModule&& from) noexcept
    : BiotAppModule() {
    *this = ::std::move(from);
  }

  inline BiotAppModule& operator=(const BiotAppModule& from) {
    CopyFrom(from);
    return *this;
  }
  inline BiotAppModule& operator=(BiotAppModule&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BiotAppModule& default_instance() {
    return *internal_default_instance();
  }
  static inline const BiotAppModule* internal_default_instance() {
    return reinterpret_cast<const BiotAppModule*>(
               &_BiotAppModule_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(BiotAppModule& a, BiotAppModule& b) {
    a.Swap(&b);
  }
  inline void Swap(BiotAppModule* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BiotAppModule* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BiotAppModule* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BiotAppModule>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BiotAppModule& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const BiotAppModule& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BiotAppModule* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "biot.BiotAppModule";
  }
  protected:
  explicit BiotAppModule(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHardwareFieldNumber = 1,
    kDeviceFieldNumber = 2,
    kNetworkFieldNumber = 3,
    kDatabaseFieldNumber = 4,
    kStorageFieldNumber = 5,
    kMediaFieldNumber = 6,
    kSubsysFieldNumber = 7,
  };
  // .biot.BiotAppHardware hardware = 1;
  bool has_hardware() const;
  private:
  bool _internal_has_hardware() const;
  public:
  void clear_hardware();
  const ::biot::BiotAppHardware& hardware() const;
  PROTOBUF_NODISCARD ::biot::BiotAppHardware* release_hardware();
  ::biot::BiotAppHardware* mutable_hardware();
  void set_allocated_hardware(::biot::BiotAppHardware* hardware);
  private:
  const ::biot::BiotAppHardware& _internal_hardware() const;
  ::biot::BiotAppHardware* _internal_mutable_hardware();
  public:
  void unsafe_arena_set_allocated_hardware(
      ::biot::BiotAppHardware* hardware);
  ::biot::BiotAppHardware* unsafe_arena_release_hardware();

  // .biot.BiotAppDevice device = 2;
  bool has_device() const;
  private:
  bool _internal_has_device() const;
  public:
  void clear_device();
  const ::biot::BiotAppDevice& device() const;
  PROTOBUF_NODISCARD ::biot::BiotAppDevice* release_device();
  ::biot::BiotAppDevice* mutable_device();
  void set_allocated_device(::biot::BiotAppDevice* device);
  private:
  const ::biot::BiotAppDevice& _internal_device() const;
  ::biot::BiotAppDevice* _internal_mutable_device();
  public:
  void unsafe_arena_set_allocated_device(
      ::biot::BiotAppDevice* device);
  ::biot::BiotAppDevice* unsafe_arena_release_device();

  // .biot.BiotAppNetwork network = 3;
  bool has_network() const;
  private:
  bool _internal_has_network() const;
  public:
  void clear_network();
  const ::biot::BiotAppNetwork& network() const;
  PROTOBUF_NODISCARD ::biot::BiotAppNetwork* release_network();
  ::biot::BiotAppNetwork* mutable_network();
  void set_allocated_network(::biot::BiotAppNetwork* network);
  private:
  const ::biot::BiotAppNetwork& _internal_network() const;
  ::biot::BiotAppNetwork* _internal_mutable_network();
  public:
  void unsafe_arena_set_allocated_network(
      ::biot::BiotAppNetwork* network);
  ::biot::BiotAppNetwork* unsafe_arena_release_network();

  // .biot.BiotAppDb database = 4;
  bool has_database() const;
  private:
  bool _internal_has_database() const;
  public:
  void clear_database();
  const ::biot::BiotAppDb& database() const;
  PROTOBUF_NODISCARD ::biot::BiotAppDb* release_database();
  ::biot::BiotAppDb* mutable_database();
  void set_allocated_database(::biot::BiotAppDb* database);
  private:
  const ::biot::BiotAppDb& _internal_database() const;
  ::biot::BiotAppDb* _internal_mutable_database();
  public:
  void unsafe_arena_set_allocated_database(
      ::biot::BiotAppDb* database);
  ::biot::BiotAppDb* unsafe_arena_release_database();

  // .biot.BiotAppStorage storage = 5;
  bool has_storage() const;
  private:
  bool _internal_has_storage() const;
  public:
  void clear_storage();
  const ::biot::BiotAppStorage& storage() const;
  PROTOBUF_NODISCARD ::biot::BiotAppStorage* release_storage();
  ::biot::BiotAppStorage* mutable_storage();
  void set_allocated_storage(::biot::BiotAppStorage* storage);
  private:
  const ::biot::BiotAppStorage& _internal_storage() const;
  ::biot::BiotAppStorage* _internal_mutable_storage();
  public:
  void unsafe_arena_set_allocated_storage(
      ::biot::BiotAppStorage* storage);
  ::biot::BiotAppStorage* unsafe_arena_release_storage();

  // .biot.BiotAppMedia media = 6;
  bool has_media() const;
  private:
  bool _internal_has_media() const;
  public:
  void clear_media();
  const ::biot::BiotAppMedia& media() const;
  PROTOBUF_NODISCARD ::biot::BiotAppMedia* release_media();
  ::biot::BiotAppMedia* mutable_media();
  void set_allocated_media(::biot::BiotAppMedia* media);
  private:
  const ::biot::BiotAppMedia& _internal_media() const;
  ::biot::BiotAppMedia* _internal_mutable_media();
  public:
  void unsafe_arena_set_allocated_media(
      ::biot::BiotAppMedia* media);
  ::biot::BiotAppMedia* unsafe_arena_release_media();

  // .biot.BiotAppSubsys subsys = 7;
  bool has_subsys() const;
  private:
  bool _internal_has_subsys() const;
  public:
  void clear_subsys();
  const ::biot::BiotAppSubsys& subsys() const;
  PROTOBUF_NODISCARD ::biot::BiotAppSubsys* release_subsys();
  ::biot::BiotAppSubsys* mutable_subsys();
  void set_allocated_subsys(::biot::BiotAppSubsys* subsys);
  private:
  const ::biot::BiotAppSubsys& _internal_subsys() const;
  ::biot::BiotAppSubsys* _internal_mutable_subsys();
  public:
  void unsafe_arena_set_allocated_subsys(
      ::biot::BiotAppSubsys* subsys);
  ::biot::BiotAppSubsys* unsafe_arena_release_subsys();

  // @@protoc_insertion_point(class_scope:biot.BiotAppModule)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::biot::BiotAppHardware* hardware_;
    ::biot::BiotAppDevice* device_;
    ::biot::BiotAppNetwork* network_;
    ::biot::BiotAppDb* database_;
    ::biot::BiotAppStorage* storage_;
    ::biot::BiotAppMedia* media_;
    ::biot::BiotAppSubsys* subsys_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_param_5fmodule_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BiotAppModule

// .biot.BiotAppHardware hardware = 1;
inline bool BiotAppModule::_internal_has_hardware() const {
  return this != internal_default_instance() && _impl_.hardware_ != nullptr;
}
inline bool BiotAppModule::has_hardware() const {
  return _internal_has_hardware();
}
inline const ::biot::BiotAppHardware& BiotAppModule::_internal_hardware() const {
  const ::biot::BiotAppHardware* p = _impl_.hardware_;
  return p != nullptr ? *p : reinterpret_cast<const ::biot::BiotAppHardware&>(
      ::biot::_BiotAppHardware_default_instance_);
}
inline const ::biot::BiotAppHardware& BiotAppModule::hardware() const {
  // @@protoc_insertion_point(field_get:biot.BiotAppModule.hardware)
  return _internal_hardware();
}
inline void BiotAppModule::unsafe_arena_set_allocated_hardware(
    ::biot::BiotAppHardware* hardware) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.hardware_);
  }
  _impl_.hardware_ = hardware;
  if (hardware) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:biot.BiotAppModule.hardware)
}
inline ::biot::BiotAppHardware* BiotAppModule::release_hardware() {
  
  ::biot::BiotAppHardware* temp = _impl_.hardware_;
  _impl_.hardware_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::biot::BiotAppHardware* BiotAppModule::unsafe_arena_release_hardware() {
  // @@protoc_insertion_point(field_release:biot.BiotAppModule.hardware)
  
  ::biot::BiotAppHardware* temp = _impl_.hardware_;
  _impl_.hardware_ = nullptr;
  return temp;
}
inline ::biot::BiotAppHardware* BiotAppModule::_internal_mutable_hardware() {
  
  if (_impl_.hardware_ == nullptr) {
    auto* p = CreateMaybeMessage<::biot::BiotAppHardware>(GetArenaForAllocation());
    _impl_.hardware_ = p;
  }
  return _impl_.hardware_;
}
inline ::biot::BiotAppHardware* BiotAppModule::mutable_hardware() {
  ::biot::BiotAppHardware* _msg = _internal_mutable_hardware();
  // @@protoc_insertion_point(field_mutable:biot.BiotAppModule.hardware)
  return _msg;
}
inline void BiotAppModule::set_allocated_hardware(::biot::BiotAppHardware* hardware) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.hardware_);
  }
  if (hardware) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(hardware));
    if (message_arena != submessage_arena) {
      hardware = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, hardware, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.hardware_ = hardware;
  // @@protoc_insertion_point(field_set_allocated:biot.BiotAppModule.hardware)
}

// .biot.BiotAppDevice device = 2;
inline bool BiotAppModule::_internal_has_device() const {
  return this != internal_default_instance() && _impl_.device_ != nullptr;
}
inline bool BiotAppModule::has_device() const {
  return _internal_has_device();
}
inline const ::biot::BiotAppDevice& BiotAppModule::_internal_device() const {
  const ::biot::BiotAppDevice* p = _impl_.device_;
  return p != nullptr ? *p : reinterpret_cast<const ::biot::BiotAppDevice&>(
      ::biot::_BiotAppDevice_default_instance_);
}
inline const ::biot::BiotAppDevice& BiotAppModule::device() const {
  // @@protoc_insertion_point(field_get:biot.BiotAppModule.device)
  return _internal_device();
}
inline void BiotAppModule::unsafe_arena_set_allocated_device(
    ::biot::BiotAppDevice* device) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.device_);
  }
  _impl_.device_ = device;
  if (device) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:biot.BiotAppModule.device)
}
inline ::biot::BiotAppDevice* BiotAppModule::release_device() {
  
  ::biot::BiotAppDevice* temp = _impl_.device_;
  _impl_.device_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::biot::BiotAppDevice* BiotAppModule::unsafe_arena_release_device() {
  // @@protoc_insertion_point(field_release:biot.BiotAppModule.device)
  
  ::biot::BiotAppDevice* temp = _impl_.device_;
  _impl_.device_ = nullptr;
  return temp;
}
inline ::biot::BiotAppDevice* BiotAppModule::_internal_mutable_device() {
  
  if (_impl_.device_ == nullptr) {
    auto* p = CreateMaybeMessage<::biot::BiotAppDevice>(GetArenaForAllocation());
    _impl_.device_ = p;
  }
  return _impl_.device_;
}
inline ::biot::BiotAppDevice* BiotAppModule::mutable_device() {
  ::biot::BiotAppDevice* _msg = _internal_mutable_device();
  // @@protoc_insertion_point(field_mutable:biot.BiotAppModule.device)
  return _msg;
}
inline void BiotAppModule::set_allocated_device(::biot::BiotAppDevice* device) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.device_);
  }
  if (device) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(device));
    if (message_arena != submessage_arena) {
      device = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, device, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.device_ = device;
  // @@protoc_insertion_point(field_set_allocated:biot.BiotAppModule.device)
}

// .biot.BiotAppNetwork network = 3;
inline bool BiotAppModule::_internal_has_network() const {
  return this != internal_default_instance() && _impl_.network_ != nullptr;
}
inline bool BiotAppModule::has_network() const {
  return _internal_has_network();
}
inline const ::biot::BiotAppNetwork& BiotAppModule::_internal_network() const {
  const ::biot::BiotAppNetwork* p = _impl_.network_;
  return p != nullptr ? *p : reinterpret_cast<const ::biot::BiotAppNetwork&>(
      ::biot::_BiotAppNetwork_default_instance_);
}
inline const ::biot::BiotAppNetwork& BiotAppModule::network() const {
  // @@protoc_insertion_point(field_get:biot.BiotAppModule.network)
  return _internal_network();
}
inline void BiotAppModule::unsafe_arena_set_allocated_network(
    ::biot::BiotAppNetwork* network) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.network_);
  }
  _impl_.network_ = network;
  if (network) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:biot.BiotAppModule.network)
}
inline ::biot::BiotAppNetwork* BiotAppModule::release_network() {
  
  ::biot::BiotAppNetwork* temp = _impl_.network_;
  _impl_.network_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::biot::BiotAppNetwork* BiotAppModule::unsafe_arena_release_network() {
  // @@protoc_insertion_point(field_release:biot.BiotAppModule.network)
  
  ::biot::BiotAppNetwork* temp = _impl_.network_;
  _impl_.network_ = nullptr;
  return temp;
}
inline ::biot::BiotAppNetwork* BiotAppModule::_internal_mutable_network() {
  
  if (_impl_.network_ == nullptr) {
    auto* p = CreateMaybeMessage<::biot::BiotAppNetwork>(GetArenaForAllocation());
    _impl_.network_ = p;
  }
  return _impl_.network_;
}
inline ::biot::BiotAppNetwork* BiotAppModule::mutable_network() {
  ::biot::BiotAppNetwork* _msg = _internal_mutable_network();
  // @@protoc_insertion_point(field_mutable:biot.BiotAppModule.network)
  return _msg;
}
inline void BiotAppModule::set_allocated_network(::biot::BiotAppNetwork* network) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.network_);
  }
  if (network) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(network));
    if (message_arena != submessage_arena) {
      network = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, network, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.network_ = network;
  // @@protoc_insertion_point(field_set_allocated:biot.BiotAppModule.network)
}

// .biot.BiotAppDb database = 4;
inline bool BiotAppModule::_internal_has_database() const {
  return this != internal_default_instance() && _impl_.database_ != nullptr;
}
inline bool BiotAppModule::has_database() const {
  return _internal_has_database();
}
inline const ::biot::BiotAppDb& BiotAppModule::_internal_database() const {
  const ::biot::BiotAppDb* p = _impl_.database_;
  return p != nullptr ? *p : reinterpret_cast<const ::biot::BiotAppDb&>(
      ::biot::_BiotAppDb_default_instance_);
}
inline const ::biot::BiotAppDb& BiotAppModule::database() const {
  // @@protoc_insertion_point(field_get:biot.BiotAppModule.database)
  return _internal_database();
}
inline void BiotAppModule::unsafe_arena_set_allocated_database(
    ::biot::BiotAppDb* database) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.database_);
  }
  _impl_.database_ = database;
  if (database) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:biot.BiotAppModule.database)
}
inline ::biot::BiotAppDb* BiotAppModule::release_database() {
  
  ::biot::BiotAppDb* temp = _impl_.database_;
  _impl_.database_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::biot::BiotAppDb* BiotAppModule::unsafe_arena_release_database() {
  // @@protoc_insertion_point(field_release:biot.BiotAppModule.database)
  
  ::biot::BiotAppDb* temp = _impl_.database_;
  _impl_.database_ = nullptr;
  return temp;
}
inline ::biot::BiotAppDb* BiotAppModule::_internal_mutable_database() {
  
  if (_impl_.database_ == nullptr) {
    auto* p = CreateMaybeMessage<::biot::BiotAppDb>(GetArenaForAllocation());
    _impl_.database_ = p;
  }
  return _impl_.database_;
}
inline ::biot::BiotAppDb* BiotAppModule::mutable_database() {
  ::biot::BiotAppDb* _msg = _internal_mutable_database();
  // @@protoc_insertion_point(field_mutable:biot.BiotAppModule.database)
  return _msg;
}
inline void BiotAppModule::set_allocated_database(::biot::BiotAppDb* database) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.database_);
  }
  if (database) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(database));
    if (message_arena != submessage_arena) {
      database = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, database, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.database_ = database;
  // @@protoc_insertion_point(field_set_allocated:biot.BiotAppModule.database)
}

// .biot.BiotAppStorage storage = 5;
inline bool BiotAppModule::_internal_has_storage() const {
  return this != internal_default_instance() && _impl_.storage_ != nullptr;
}
inline bool BiotAppModule::has_storage() const {
  return _internal_has_storage();
}
inline const ::biot::BiotAppStorage& BiotAppModule::_internal_storage() const {
  const ::biot::BiotAppStorage* p = _impl_.storage_;
  return p != nullptr ? *p : reinterpret_cast<const ::biot::BiotAppStorage&>(
      ::biot::_BiotAppStorage_default_instance_);
}
inline const ::biot::BiotAppStorage& BiotAppModule::storage() const {
  // @@protoc_insertion_point(field_get:biot.BiotAppModule.storage)
  return _internal_storage();
}
inline void BiotAppModule::unsafe_arena_set_allocated_storage(
    ::biot::BiotAppStorage* storage) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.storage_);
  }
  _impl_.storage_ = storage;
  if (storage) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:biot.BiotAppModule.storage)
}
inline ::biot::BiotAppStorage* BiotAppModule::release_storage() {
  
  ::biot::BiotAppStorage* temp = _impl_.storage_;
  _impl_.storage_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::biot::BiotAppStorage* BiotAppModule::unsafe_arena_release_storage() {
  // @@protoc_insertion_point(field_release:biot.BiotAppModule.storage)
  
  ::biot::BiotAppStorage* temp = _impl_.storage_;
  _impl_.storage_ = nullptr;
  return temp;
}
inline ::biot::BiotAppStorage* BiotAppModule::_internal_mutable_storage() {
  
  if (_impl_.storage_ == nullptr) {
    auto* p = CreateMaybeMessage<::biot::BiotAppStorage>(GetArenaForAllocation());
    _impl_.storage_ = p;
  }
  return _impl_.storage_;
}
inline ::biot::BiotAppStorage* BiotAppModule::mutable_storage() {
  ::biot::BiotAppStorage* _msg = _internal_mutable_storage();
  // @@protoc_insertion_point(field_mutable:biot.BiotAppModule.storage)
  return _msg;
}
inline void BiotAppModule::set_allocated_storage(::biot::BiotAppStorage* storage) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.storage_);
  }
  if (storage) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(storage));
    if (message_arena != submessage_arena) {
      storage = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, storage, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.storage_ = storage;
  // @@protoc_insertion_point(field_set_allocated:biot.BiotAppModule.storage)
}

// .biot.BiotAppMedia media = 6;
inline bool BiotAppModule::_internal_has_media() const {
  return this != internal_default_instance() && _impl_.media_ != nullptr;
}
inline bool BiotAppModule::has_media() const {
  return _internal_has_media();
}
inline const ::biot::BiotAppMedia& BiotAppModule::_internal_media() const {
  const ::biot::BiotAppMedia* p = _impl_.media_;
  return p != nullptr ? *p : reinterpret_cast<const ::biot::BiotAppMedia&>(
      ::biot::_BiotAppMedia_default_instance_);
}
inline const ::biot::BiotAppMedia& BiotAppModule::media() const {
  // @@protoc_insertion_point(field_get:biot.BiotAppModule.media)
  return _internal_media();
}
inline void BiotAppModule::unsafe_arena_set_allocated_media(
    ::biot::BiotAppMedia* media) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.media_);
  }
  _impl_.media_ = media;
  if (media) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:biot.BiotAppModule.media)
}
inline ::biot::BiotAppMedia* BiotAppModule::release_media() {
  
  ::biot::BiotAppMedia* temp = _impl_.media_;
  _impl_.media_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::biot::BiotAppMedia* BiotAppModule::unsafe_arena_release_media() {
  // @@protoc_insertion_point(field_release:biot.BiotAppModule.media)
  
  ::biot::BiotAppMedia* temp = _impl_.media_;
  _impl_.media_ = nullptr;
  return temp;
}
inline ::biot::BiotAppMedia* BiotAppModule::_internal_mutable_media() {
  
  if (_impl_.media_ == nullptr) {
    auto* p = CreateMaybeMessage<::biot::BiotAppMedia>(GetArenaForAllocation());
    _impl_.media_ = p;
  }
  return _impl_.media_;
}
inline ::biot::BiotAppMedia* BiotAppModule::mutable_media() {
  ::biot::BiotAppMedia* _msg = _internal_mutable_media();
  // @@protoc_insertion_point(field_mutable:biot.BiotAppModule.media)
  return _msg;
}
inline void BiotAppModule::set_allocated_media(::biot::BiotAppMedia* media) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.media_);
  }
  if (media) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(media));
    if (message_arena != submessage_arena) {
      media = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, media, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.media_ = media;
  // @@protoc_insertion_point(field_set_allocated:biot.BiotAppModule.media)
}

// .biot.BiotAppSubsys subsys = 7;
inline bool BiotAppModule::_internal_has_subsys() const {
  return this != internal_default_instance() && _impl_.subsys_ != nullptr;
}
inline bool BiotAppModule::has_subsys() const {
  return _internal_has_subsys();
}
inline const ::biot::BiotAppSubsys& BiotAppModule::_internal_subsys() const {
  const ::biot::BiotAppSubsys* p = _impl_.subsys_;
  return p != nullptr ? *p : reinterpret_cast<const ::biot::BiotAppSubsys&>(
      ::biot::_BiotAppSubsys_default_instance_);
}
inline const ::biot::BiotAppSubsys& BiotAppModule::subsys() const {
  // @@protoc_insertion_point(field_get:biot.BiotAppModule.subsys)
  return _internal_subsys();
}
inline void BiotAppModule::unsafe_arena_set_allocated_subsys(
    ::biot::BiotAppSubsys* subsys) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.subsys_);
  }
  _impl_.subsys_ = subsys;
  if (subsys) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:biot.BiotAppModule.subsys)
}
inline ::biot::BiotAppSubsys* BiotAppModule::release_subsys() {
  
  ::biot::BiotAppSubsys* temp = _impl_.subsys_;
  _impl_.subsys_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::biot::BiotAppSubsys* BiotAppModule::unsafe_arena_release_subsys() {
  // @@protoc_insertion_point(field_release:biot.BiotAppModule.subsys)
  
  ::biot::BiotAppSubsys* temp = _impl_.subsys_;
  _impl_.subsys_ = nullptr;
  return temp;
}
inline ::biot::BiotAppSubsys* BiotAppModule::_internal_mutable_subsys() {
  
  if (_impl_.subsys_ == nullptr) {
    auto* p = CreateMaybeMessage<::biot::BiotAppSubsys>(GetArenaForAllocation());
    _impl_.subsys_ = p;
  }
  return _impl_.subsys_;
}
inline ::biot::BiotAppSubsys* BiotAppModule::mutable_subsys() {
  ::biot::BiotAppSubsys* _msg = _internal_mutable_subsys();
  // @@protoc_insertion_point(field_mutable:biot.BiotAppModule.subsys)
  return _msg;
}
inline void BiotAppModule::set_allocated_subsys(::biot::BiotAppSubsys* subsys) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.subsys_);
  }
  if (subsys) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(subsys));
    if (message_arena != submessage_arena) {
      subsys = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, subsys, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.subsys_ = subsys;
  // @@protoc_insertion_point(field_set_allocated:biot.BiotAppModule.subsys)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace biot

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_param_5fmodule_2eproto
